# Generated by Django 4.2.29 on 2026-04-30 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '编制中'), ('reviewing', '审核中'), ('locked', '终版锁定'), ('archived', '已归档')], default='draft', max_length=32)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '预算周期',
                'verbose_name_plural': '预算周期',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='BudgetTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('not_started', '未开始'), ('drafting', '编制中'), ('secondary_review', '待二级部门负责人审批'), ('secondary_rejected', '二级部门负责人退回'), ('secondary_approved', '二级部门负责人已审批'), ('pulled_to_primary', '已被一级部门拉取'), ('primary_review', '一级预算审核中'), ('final_locked', '终版锁定')], default='not_started', max_length=32)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='budget_cycles.budgetcycle')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_tasks', to='orgs.department')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_budget_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '预算任务',
                'verbose_name_plural': '预算任务',
                'ordering': ['cycle', 'department__sort_order'],
                'unique_together': {('cycle', 'department')},
            },
        ),
    ]
