# Generated by Django 4.2.29 on 2026-04-30 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_type', models.CharField(max_length=64)),
                ('target_id', models.UUIDField()),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已退回'), ('cancelled', '已取消')], default='pending', max_length=32)),
                ('current_node', models.PositiveIntegerField(default=1)),
                ('submitted_version_label', models.CharField(blank=True, max_length=64)),
                ('dashboard_context', models.JSONField(blank=True, default=dict)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests', to='orgs.department')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '审批请求',
                'verbose_name_plural': '审批请求',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('pending', '待处理'), ('approved', '通过'), ('rejected', '退回')], default='pending', max_length=32)),
                ('comment', models.TextField(blank=True)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_steps', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='approvals.approvalrequest')),
            ],
            options={
                'verbose_name': '审批节点',
                'verbose_name_plural': '审批节点',
                'ordering': ['request', 'node'],
                'unique_together': {('request', 'node', 'approver')},
            },
        ),
    ]
