# Generated by Django 4.2.29 on 2026-04-30 14:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masterdata', '0001_initial'),
        ('budget_cycles', '0001_initial'),
        ('budget_templates', '0001_initial'),
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetBook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense_type', models.CharField(choices=[('opex', 'OPEX'), ('capex', 'CAPEX')], max_length=16)),
                ('source_type', models.CharField(choices=[('self_built', '二级部门自编'), ('special', '专题生成'), ('ss_public', 'SS public'), ('group_allocation', '集团分摊'), ('primary_consolidated', '一级总表')], default='self_built', max_length=32)),
                ('status', models.CharField(choices=[('drafting', '编制中'), ('reviewing', '审核中'), ('approved', '已审批'), ('locked', '已锁定')], default='drafting', max_length=32)),
            ],
            options={
                'verbose_name': '预算表',
                'verbose_name_plural': '预算表',
                'ordering': ['cycle', 'department__sort_order', 'expense_type'],
            },
        ),
        migrations.CreateModel(
            name='BudgetVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_no', models.PositiveIntegerField(default=0, help_text='Draft 可为 0，审批通过后生成正式版本号。')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', '送审中'), ('approved', 'Approved'), ('rejected', '已退回'), ('final', 'Final')], default='draft', max_length=32)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('snapshot_hash', models.CharField(blank=True, max_length=128)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_budget_versions', to=settings.AUTH_USER_MODEL)),
                ('base_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_versions', to='budgets.budgetversion')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='budgets.budgetbook')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_budget_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '预算版本',
                'verbose_name_plural': '预算版本',
                'ordering': ['book', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_no', models.PositiveIntegerField(default=0)),
                ('budget_no', models.CharField(blank=True, max_length=128)),
                ('cost_center_code', models.CharField(blank=True, max_length=64)),
                ('gl_amount_code', models.CharField(blank=True, max_length=64)),
                ('description', models.CharField(max_length=255)),
                ('reason', models.TextField(blank=True)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('dynamic_data', models.JSONField(blank=True, default=dict)),
                ('local_comments', models.JSONField(blank=True, default=dict)),
                ('admin_annotations', models.JSONField(blank=True, default=dict)),
                ('source_ref_type', models.CharField(blank=True, max_length=64)),
                ('source_ref_id', models.UUIDField(blank=True, null=True)),
                ('editable_by_secondary', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_lines', to='masterdata.category')),
                ('category_l1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_l1_lines', to='masterdata.category')),
                ('category_l2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_l2_lines', to='masterdata.category')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines', to='orgs.department')),
                ('product_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_lines', to='masterdata.productline')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_lines', to='masterdata.project')),
                ('project_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_lines', to='masterdata.projectcategory')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_lines', to='masterdata.region')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_lines', to='masterdata.vendor')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='budgets.budgetversion')),
            ],
            options={
                'verbose_name': '预算条目',
                'verbose_name_plural': '预算条目',
                'ordering': ['version', 'line_no'],
            },
        ),
        migrations.AddField(
            model_name='budgetbook',
            name='current_draft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_for_books', to='budgets.budgetversion'),
        ),
        migrations.AddField(
            model_name='budgetbook',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_books', to='budget_cycles.budgetcycle'),
        ),
        migrations.AddField(
            model_name='budgetbook',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_books', to='orgs.department'),
        ),
        migrations.AddField(
            model_name='budgetbook',
            name='latest_approved_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_for_books', to='budgets.budgetversion'),
        ),
        migrations.AddField(
            model_name='budgetbook',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_books', to='budget_templates.budgettemplate'),
        ),
        migrations.CreateModel(
            name='BudgetMonthlyPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_plans', to='budgets.budgetline')),
            ],
            options={
                'verbose_name': '预算月度计划',
                'verbose_name_plural': '预算月度计划',
                'ordering': ['line', 'month'],
                'unique_together': {('line', 'month')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='budgetbook',
            unique_together={('cycle', 'department', 'expense_type', 'source_type')},
        ),
    ]
