# Generated by Django 4.2.29 on 2026-05-02 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_name', models.CharField(blank=True, max_length=255)),
                ('mode', models.CharField(choices=[('append', '追加导入'), ('replace', '覆盖导入')], default='append', max_length=16)),
                ('status', models.CharField(choices=[('processing', '处理中'), ('success', '成功'), ('failed', '失败')], default='processing', max_length=16)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('imported_rows', models.PositiveIntegerField(default=0)),
                ('error_rows', models.PositiveIntegerField(default=0)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='budgets.budgetversion')),
            ],
            options={
                'verbose_name': '导入任务',
                'verbose_name_plural': '导入任务',
                'ordering': ['-created_at'],
            },
        ),
    ]
