# Generated by Django 4.2.29 on 2026-05-02 13:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionSourceRegistryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=128, unique=True)),
                ('label', models.CharField(max_length=128)),
                ('kind', models.CharField(default='masterdata', max_length=32)),
                ('endpoint', models.CharField(max_length=255)),
                ('value_field', models.CharField(default='code', max_length=64)),
                ('label_field', models.CharField(default='name', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': '选项源注册表',
                'verbose_name_plural': '选项源注册表',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='aliases',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='category',
            name='keep_history',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='legacy_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='category',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productline',
            name='aliases',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='productline',
            name='keep_history',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productline',
            name='legacy_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='productline',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='aliases',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='keep_history',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='legacy_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='project',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='aliases',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='keep_history',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='legacy_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='region',
            name='aliases',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='region',
            name='keep_history',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='region',
            name='legacy_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='region',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='aliases',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='vendor',
            name='keep_history',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='legacy_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='vendor',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='GLAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('legacy_name', models.CharField(blank=True, max_length=128)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('keep_history', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('expense_type', models.CharField(blank=True, max_length=16)),
                ('mapped_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gl_accounts', to='masterdata.category')),
                ('mapped_project_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gl_accounts', to='masterdata.projectcategory')),
            ],
            options={
                'verbose_name': 'GL Account',
                'verbose_name_plural': 'GL Account',
                'ordering': ['sort_order', 'code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('legacy_name', models.CharField(blank=True, max_length=128)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('keep_history', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_centers', to='orgs.department')),
            ],
            options={
                'verbose_name': '成本中心',
                'verbose_name_plural': '成本中心',
                'ordering': ['sort_order', 'code'],
                'abstract': False,
            },
        ),
    ]
