# Generated by Django 4.2.29 on 2026-04-30 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('scope', models.CharField(choices=[('personal', '个人'), ('department', '部门'), ('global', '全局')], default='personal', max_length=32)),
                ('version_context', models.CharField(default='latest_approved', max_length=64)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_configs', to='orgs.department')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard 配置',
                'verbose_name_plural': 'Dashboard 配置',
                'ordering': ['scope', 'name'],
            },
        ),
    ]
