# Generated by Django 4.2.29 on 2026-05-02 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budgets', '0003_allocationupload'),
        ('budget_cycles', '0001_initial'),
        ('orgs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('expense_type', models.CharField(choices=[('opex', 'OPEX'), ('capex', 'CAPEX')], default='opex', max_length=16)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '启用'), ('archived', '归档')], default='draft', max_length=16)),
                ('target_mode', models.CharField(choices=[('secondary', '挂到二级部门'), ('ss_public', '挂到 SS public')], default='secondary', max_length=16)),
                ('schema', models.JSONField(blank=True, default=list)),
                ('default_payload', models.JSONField(blank=True, default=list)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_templates', to='budget_cycles.budgetcycle')),
                ('target_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_demand_templates', to='orgs.department')),
            ],
            options={
                'verbose_name': '专题需求模板',
                'verbose_name_plural': '专题需求模板',
                'ordering': ['cycle', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DemandSheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('confirmed', '已确认'), ('generated', '已生成预算')], default='draft', max_length=16)),
                ('payload', models.JSONField(blank=True, default=list)),
                ('generated_line_count', models.PositiveIntegerField(default=0)),
                ('generated_budget_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_demand_sheets', to='budgets.budgetbook')),
                ('generated_budget_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_demand_sheets', to='budgets.budgetversion')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_demand_sheets', to=settings.AUTH_USER_MODEL)),
                ('target_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demand_sheets', to='orgs.department')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='demands.demandtemplate')),
            ],
            options={
                'verbose_name': '专题需求表',
                'verbose_name_plural': '专题需求表',
                'ordering': ['-created_at'],
            },
        ),
    ]
