# Generated by Django 4.2.29 on 2026-05-02 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandsheet',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandsheet',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_demand_sheets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demandsheet',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandsheet',
            name='generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandsheet',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_demand_sheets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demandsheet',
            name='generated_payload_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='demandsheet',
            name='latest_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='demandsheet',
            name='schema_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='demandsheet',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandsheet',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_demand_sheets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='demandsheet',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('confirmed', '已确认'), ('generated', '已生成预算')], default='draft', max_length=16),
        ),
    ]
