# Generated by Django 4.2.29 on 2026-04-30 14:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budget_cycles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('expense_type', models.CharField(choices=[('opex', 'OPEX'), ('capex', 'CAPEX'), ('special', '专题表单')], max_length=16)),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '启用'), ('archived', '归档')], default='draft', max_length=16)),
                ('copied_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copied_templates', to='budget_templates.budgettemplate')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='budget_cycles.budgetcycle')),
            ],
            options={
                'verbose_name': '预算模板',
                'verbose_name_plural': '预算模板',
                'ordering': ['cycle', 'expense_type', 'schema_version'],
                'unique_together': {('cycle', 'expense_type', 'schema_version')},
            },
        ),
        migrations.CreateModel(
            name='TemplateField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=128)),
                ('data_type', models.CharField(choices=[('text', '文本'), ('number', '数字'), ('money', '金额'), ('date', '日期'), ('boolean', '布尔'), ('option', '选项'), ('json', 'JSON')], max_length=16)),
                ('input_type', models.CharField(choices=[('text', '文本输入'), ('number', '数字输入'), ('select', '下拉'), ('multi_select', '多选'), ('date', '日期'), ('formula', '公式'), ('user', '用户选择'), ('department', '部门选择'), ('project', '项目选择')], default='text', max_length=32)),
                ('required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(default=160)),
                ('option_source', models.CharField(blank=True, max_length=128)),
                ('formula', models.CharField(blank=True, max_length=512)),
                ('visible_rules', models.JSONField(blank=True, default=dict)),
                ('editable_rules', models.JSONField(blank=True, default=dict)),
                ('approval_included', models.BooleanField(default=True)),
                ('dashboard_enabled', models.BooleanField(default=False)),
                ('import_aliases', models.JSONField(blank=True, default=list)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='budget_templates.budgettemplate')),
            ],
            options={
                'verbose_name': '模板字段',
                'verbose_name_plural': '模板字段',
                'ordering': ['template', 'order', 'code'],
                'unique_together': {('template', 'code')},
            },
        ),
    ]
